### ISSUE TITLE
Font Scaling not considered

### ISSUE THREAD

**Issue by amadeusp** [oae/gnome-shell-pano#104]
If you change the font scaling in Tweaks, Pano does not take this into account. This means that Pano still shows the same small font size even with scaling values of e.g. 1.5 or 2, instead of (as expected) displaying the font larger according to the defined scaling factor. Attached are two screen grabs with 1.5 and 2 as scaling factor.

https://unsee.cc/album#9sL44KfBiMvJ3rkc
https://unsee.cc/album#upykN8Gp5iLyklwE

My system:
- OS: Manjaro 22.0.0 Sikaris
- Kernel: x86_64 Linux 6.0.0-1-MANJARO
- Resolution: 1920x1080
- DE: GNOME 42.3
- WM: Mutter
- WM Theme: Adwaita-maia-dark
- GTK Theme: Adwaita [GTK2/3]
- Icon Theme: Papirus
- Font: Cantarell 11
- CPU: AMD Ryzen 7 PRO 4750U with Radeon Graphics @ 16x 1.7GHz
- GPU: AMD RENOIR (LLVM 14.0.6, DRM 3.48, 6.0.0-1-MANJARO)
- RAM: 9297MiB / 29806MiB
- Wayland
- PipeWire

**Comment by Bananaman** [comment]
@oae I agree with this. Pano is beautiful but it's also totally unreadable on my 4K screen.

Two things are needed:

1. Apply the screen scaling factor from the GNOME screen that it's rendering Pano on. I use 200% on my screen. So let's say your current Pano font is 14px, which means that on my screen, it currently appears like if it's 7px (super small) because Pano's font isn't being scaled properly for the DPI of this screen. With proper scaling it would render the font at 14x2 = 28px. The "title" text on pano which says stuff like "Link" or "Text" is readable, but the sub-info like "about 1 hour ago" and the text previews are too small to be readable.
2. Also would be VERY USEFUL to have an actual font size percentage slider inside Pano's settings, to be able to further fine-tune the relative font size.

Here's the algorithm I envision:

```
( Pano'sIntendedFontSize (ie 14px) * SettingsScaleFactor (50%-400%, ie 125%) ) * GNOMEScreenScaleFactor (ie 200%)

Meaning:

( 14px * 1.25 ) * 2.0 = 35px
```

This would solve everything! :)

**Comment by oae** [comment]
I have added font customization. You can now change it in the settings.

![image](https://user-images.githubusercontent.com/1043714/222929856-b2aaa57c-5c93-447f-8a1c-a6f101658bda.png)

**Comment by Bananaman** [comment]
@oae Wow that's a very detailed way to configure things. YOU'RE AWESOME! Thank you so much!

**Comment by Bananaman** [comment]
@oae

I have configured every font now and it's looking GREAT except for the headers. Please, is there any chance that you could also add a category named "Item Headers" at the top of the list, where we can set the font for the main label and the "timestamp" fields of all clipboard items universally?

I mean these ones at the top. :)

![image](https://user-images.githubusercontent.com/38923130/224557958-3d7f6aa2-9458-4c7e-a7a2-e1f0f24f3694.png)

**Comment by Bananaman** [comment]
Oh and also this font.

Maybe call the category:

- General Settings:
- - Search Field Font
- - Item Title Font
- - Item Timestamp Font

**Comment by oae** [comment]
I have added related settings.

![image](https://user-images.githubusercontent.com/1043714/224569923-becc5e33-6629-413c-a3cf-ac193bd5b267.png)

**Comment by Bananaman** [comment]
@oae Thank you sooooo much, thank you thank you! It's beautiful! :) This is the greatest clipboard manager ever made.
