### ISSUE TITLE
TypeError: this.add_actor is not a function

### ISSUE THREAD

**Issue by blackm4c** [oae/gnome-shell-pano#294]
Just now i installed the Pano clipboard manager
i got error like GSound so i installed the require lib by following guide 
But now i get error like

```
TypeError: this.add_actor is not a function
```

https://github.com/oae/gnome-shell-pano/assets/78611909/4c65e95a-d20e-416b-a4a1-17ae0a564612

**Comment by Totto16** [comment]
Could you provide more information, like distro, distro version, gnome version and pano version?

Some of those information you can find in the settings, the other one in the extension settings:


![image](https://github.com/oae/gnome-shell-pano/assets/32566573/b1f9c9b0-d375-4322-a596-e9a85be0b635)

**Comment by blackm4c** [comment]
distro and gnome version
![image](https://github.com/oae/gnome-shell-pano/assets/78611909/237f1bba-6650-41ee-9fd1-05b31841f7ee)

pano version is 22
![panoversion](https://github.com/oae/gnome-shell-pano/assets/78611909/e130f407-8712-426c-8a01-d12cce8e4137)

**Comment by Totto16** [comment]
Than you likely bumped the supported gnome version manually, since v22 doesn't support Gnome 46, only v23 (or version >= 1001 if you use the manual built version from this repo)

v23 isn't yet published on EGO, you have to use the latest pre-release: https://github.com/oae/gnome-shell-pano/releases/tag/v23-alpha

I am closing this, since this is already fixed there, but not in v22
